<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-48G8LDM" ignored="0" name="Create Customer API Test" tests="3" failures="1" timestamp="2020-05-01T16:11:50 IST" time="9.628" errors="0">
  <testcase name="validateCreateCustomerAPIWithInvalidSecretKey" time="4.794" classname="com.w2a.APITestingFramework.testcases.CeateCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.w2a.APITestingFramework.testcases.CeateCustomerTest.validateCreateCustomerAPIWithInvalidSecretKey(CeateCustomerTest.java:40)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- validateCreateCustomerAPIWithInvalidSecretKey -->
  <testcase name="validateCreateCustomerAPIWithValidSecretKey" time="2.408" classname="com.w2a.APITestingFramework.testcases.CeateCustomerTest"/>
  <testcase name="validateCreateCustomerAPIWithValidSecretKey" time="2.236" classname="com.w2a.APITestingFramework.testcases.CeateCustomerTest"/>
</testsuite> <!-- Create Customer API Test -->
